### ISSUE TITLE
Running server.py

### ISSUE THREAD

**Issue by krishnakpandian** [insidesherpa/bank-mergeCoTechTask2#281]
python3 server3.py
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

I haven't changed any of the code yet but it is breaking initializing the app class

**Comment by krishnakpandian** [comment]
Must run datafeed/server.py and not inside the directory
