### ISSUE TITLE
server3.py not working

### ISSUE THREAD

**Issue by ARK2K** [insidesherpa/bank-mergeCoTechTask2#355]
File "C:\Users\Ankur Kushwaha\New folder\New folder\JPMC-tech-task-2-PY3\datafeed\server3.py", line 320, in <module>
    run(App())
  File "C:\Users\Ankur Kushwaha\New folder\New folder\JPMC-tech-task-2-PY3\datafeed\server3.py", line 244, in __init
    self._sim_start, _, _  = next(self._data_1)
[StopIteration[]
![error](https://user-images.githubusercontent.com/82331122/150333715-126ee11e-dacc-489a-84b8-ebde974b0f6d.png)

**Comment by sl2000stat** [comment]
Facing the same Problem here:

Traceback (most recent call last):
  File "/Users/simonleiner/PycharmProjects/JPMC-tech-task-2-PY3/datafeed/server3.py", line 320, in <module>
    run(App())
  File "/Users/simonleiner/PycharmProjects/JPMC-tech-task-2-PY3/datafeed/server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

( MAC OS)

**Comment by harshitpandey268** [comment]
Did you get the solution for this.?
