### ISSUE TITLE
NPM START

### ISSUE THREAD

**Issue by elieyounan** [insidesherpa/bank-mergeCoTechTask2#359]
I was experiencing issues using NPM install. Then I manually downloaded the modules and put them in the JPMC folder. When I do NPM start, browser loads up but doesn't show anything but "This site cannot be reached". I already checked all proxies and they're all disabled. (Note I am using a MAC system. Also NPM would not work with NVM being at v11.0.0. It wanted a higher version). This is the error I get after it says "starting the development server...."

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/NormalModule.js:434:10)
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/NormalModule.js:466:5
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/NormalModule.js:327:12
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/elieyounan/JPMC-tech-task-2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
/Users/elieyounan/JPMC-tech-task-2/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/NormalModule.js:386:16)
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/NormalModule.js:418:10
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/webpack/lib/NormalModule.js:293:13
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/elieyounan/JPMC-tech-task-2/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/elieyounan/JPMC-tech-task-2/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by elieyounan** [comment]
UPDATE : AS STATED ABOVE, I was using latest updated NVM and not the 11.0.0 because NPM was not working with such outdated version. I DOWNGRADED current NVM version from 17 to 16 and the above stated launching error does not exist anymore!
