### ISSUE TITLE
 bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild` &&  Node-gyp failed to build your package.

### ISSUE THREAD

**Issue by champ2461** [insidesherpa/bank-mergeCoTechTask2#370]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Object.fromEntries is not a function
gyp ERR! stack     at Object.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v11.0.0\node_modules\node-gyp\node_modules\@npmcli\fs\lib\fs.js:6:23)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:707:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:605:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:536:3)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:643:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:22:18)
gyp ERR! stack     at Object.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v11.0.0\node_modules\node-gyp\node_modules\@npmcli\fs\lib\index.js:2:6)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:707:30)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\OneDrive\Desktop\jp_morgan\JPMC-tech-task-2\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2022-07-16T18_45_10_570Z-debug.log

**Comment by thefledgedhurricane** [comment]
Can you provide the details about your node version?
